# ============================================================
# 05_validation.R
# Model validation for Gaussian Bayesian Network (GBN)
# ============================================================

# -------------------------------
# Setup
# -------------------------------

source("packages.R")
source("utils.R")
source("03_bn_structure.R")
source("04_parameter_learning.R")

# ============================================================
# Example workflow (template)
# ============================================================

# The following is an illustrative workflow.
# Replace `data` with your processed dataset.

# ------------------------------------------------------------
# Expected structure:
# data <- data.frame(
#   ATP_perc = numeric,
#   aSMA     = numeric,
#   Col1a1   = numeric
# )
# ------------------------------------------------------------

# -------------------------------
# Load data
# -------------------------------

data <- read.csv2("data/my_processed_data.csv")

# Ensure numeric
data <- as.data.frame(lapply(data, as.numeric))

# Ensure numeric and remove NAs (MLE fitting requires complete cases)

# ============================================================
# 1. Cross-validation setup
# ============================================================

set.seed(123)


THRESHOLD <- 1.5

n_folds <- 5
folds <- sample(rep(1:n_folds, length.out = nrow(data)))

vars <- c("ATP_perc", "aSMA", "Col1a1")

# Storage
results <- list()

# ============================================================
# 2. Cross-validation loop
# ============================================================

for (k in 1:n_folds) {
  
  train_data <- data[folds != k, ]
  test_data  <- data[folds == k, ]
  
  # Fit model on training data
  bn_fit_cv <- bn.fit(
    bn_structure,
    data = train_data,
    method = "mle"
  )
  
  n_test <- nrow(test_data)
  
  # --- initialize storage
  pred_aSMA_mean <- numeric(n_test)
  pred_Col1a1_mean <- numeric(n_test)
  
  pred_aSMA_sd <- numeric(n_test)
  pred_Col1a1_sd <- numeric(n_test)
  
  prob_aSMA_cpdist <- numeric(n_test)
  prob_Col1a1_cpdist <- numeric(n_test)
  
  
  for (i in 1:n_test) {
    
    evidence <- list(ATP_perc = test_data$ATP_perc[i])
    
    sample_dist <- cpdist(
      bn_fit_cv,
      nodes = c("aSMA", "Col1a1"),
      evidence = evidence,
      method = "lw"
    )
    
    pred_aSMA_mean[i] <- mean(sample_dist$aSMA)
    pred_Col1a1_mean[i]  <- mean(sample_dist$Col1a1)
    
    pred_aSMA_sd[i] <- sd(sample_dist$aSMA)
    pred_Col1a1_sd[i] <- sd(sample_dist$Col1a1)
    
    
    prob_aSMA_cpdist[i] <- mean(sample_dist$aSMA >= THRESHOLD)
    prob_Col1a1_cpdist[i] <- mean(sample_dist$Col1a1 >= THRESHOLD)
    
  }
  
  results[[k]] <- data.frame(
    fold = k,
    ATP_perc = test_data$ATP_perc,
    # Observed continuous
    observed_aSMA = test_data$aSMA,
    observed_Col1a1 = test_data$Col1a1,
    
    # Continuous predictions
    predicted_aSMA = pred_aSMA_mean,
    predicted_Col1a1 = pred_Col1a1_mean,
    
    # Uncertainty
    pred_aSMA_sd = pred_aSMA_sd,
    pred_Col1a1_sd = pred_Col1a1_sd,
    
    # Probabilities (cpdist)
    prob_aSMA_cpdist = prob_aSMA_cpdist,
    prob_Col1a1_cpdist = prob_Col1a1_cpdist
  
  )
}

# Combine folds
cv_results <- do.call(rbind, results)

# ============================================================
# 3. Performance metrics
# ============================================================

# R² function (simple Pearson-based proxy)
r2_aSMA <- cor(cv_results$observed_aSMA, cv_results$predicted_aSMA)^2
r2_Col1a1  <- cor(cv_results$observed_Col1a1, cv_results$predicted_Col1a1)^2

# NMSE
nmse_aSMA <- nmse(cv_results$observed_aSMA, cv_results$predicted_aSMA)
nmse_Col1a1  <- nmse(cv_results$observed_Col1a1, cv_results$predicted_Col1a1)

# AUC

# 1. Create binary ground truth from the cross-validation observations
cv_results$aSMA_high_obs   <- ifelse(cv_results$observed_aSMA >= THRESHOLD, 1, 0)
cv_results$Col1a1_high_obs <- ifelse(cv_results$observed_Col1a1 >= THRESHOLD, 1, 0)

# 2. Calculate ROC using the probabilities generated by cpdist inside the loop
roc_aSMA   <- roc(response = cv_results$aSMA_high_obs, predictor = cv_results$prob_aSMA_cpdist)
roc_Col1a1 <- roc(response = cv_results$Col1a1_high_obs, predictor = cv_results$prob_Col1a1_cpdist)


metrics <- data.frame(
  Node = c("aSMA", "Col1a1"),
  R2 = c(r2_aSMA, r2_Col1a1),
  NMSE = c(nmse_aSMA, nmse_Col1a1),
  AUC = c(auc(roc_aSMA), auc(roc_Col1a1))
)

print(metrics)
# ============================================================
# 4. Calibration plots
# ============================================================

par(mfrow = c(1,2))

plot(cv_results$observed_aSMA, cv_results$predicted_aSMA,
     main = "aSMA: Observed vs Predicted",
     xlab = "Observed", ylab = "Predicted")
abline(0,1, col = "red")

plot(cv_results$observed_Col1a1, cv_results$predicted_Col1a1,
     main = "COL1A1: Observed vs Predicted",
     xlab = "Observed", ylab = "Predicted")
abline(0,1, col = "red")

par(mfrow = c(1,1))

# ============================================================
# 5. Threshold-based classification (optional)
# ============================================================

cv_results$aSMA_high_pred <- ifelse(cv_results$predicted_aSMA >= THRESHOLD, 1, 0)
cv_results$Col1a1_high_pred <- ifelse(cv_results$predicted_Col1a1 >= THRESHOLD, 1, 0)

# ============================================================
# Notes
# ============================================================

# - Cross-validation performed using 5-fold partitioning
# - Predictions obtained via likelihood-weighted sampling (cpdist)
# - R² used as predictive correlation measure
# - NMSE used as normalized error metric
# - Calibration plots assess systematic bias
# - Threshold analysis links continuous predictions to biological states